package generate

// GeneratedByHeader is the "do not edit" marker every generated file opens
// with. Each format wraps it in its own comment syntax: TOML and shell with
// "# ", Go with "// ", and JSON Schema in $comment.
const GeneratedByHeader = "Auto-generated by cmd/generate. Do not edit."
